#!/usr/bin/env bash
set -euo pipefail

# Installs discourse/discourse_docker (if needed), deploys app.yml,
# and runs the bootstrap build. Takes 10–20 minutes on first run.
#
# Requires: .env and containers/app.yml (generated by make setup).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_DIR"

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found — run: make setup"
  exit 1
fi

if [[ ! -f containers/app.yml ]]; then
  echo "ERROR: containers/app.yml not found — run: make setup"
  exit 1
fi

set -a
# shellcheck source=../.env
source .env
set +a

DISCOURSE_DOCKER_DIR="${DISCOURSE_DOCKER_DIR:-/var/discourse}"

# -------------------------------------------------------
# Clone discourse_docker if not present
# -------------------------------------------------------
if [[ ! -d "$DISCOURSE_DOCKER_DIR" ]]; then
  echo "[bootstrap] Cloning discourse/discourse_docker to ${DISCOURSE_DOCKER_DIR}..."
  sudo git clone https://github.com/discourse/discourse_docker.git "$DISCOURSE_DOCKER_DIR"
fi

# -------------------------------------------------------
# Deploy app.yml
# -------------------------------------------------------
sudo mkdir -p "${DISCOURSE_DOCKER_DIR}/containers"
echo "[bootstrap] Deploying containers/app.yml → ${DISCOURSE_DOCKER_DIR}/containers/app.yml"
sudo cp "${PROJECT_DIR}/containers/app.yml" "${DISCOURSE_DOCKER_DIR}/containers/app.yml"

# -------------------------------------------------------
# Bootstrap
# -------------------------------------------------------
echo ""
echo "[bootstrap] Building Discourse container — this takes 10–20 minutes..."
echo ""
cd "$DISCOURSE_DOCKER_DIR"
sudo ./launcher bootstrap app

echo ""
echo "[bootstrap] Build complete. Run: make start"
